######################################################################
# Automatically generated by qmake (2.01a) ?????? ?? 6 01:13:30 2012
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += Sudoku_Solver.h
SOURCES += main.cpp Sudoku_Solver.cpp
RESOURCES += Sudoku_Solver_1.1.qrc
